language: node_js

node_js:
  - 12

jobs:
  include:
    - script: npm run build
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        script: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
